#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1
PROG=/usr/bin/vpn-runner.sh

start_service() {
    local enabled
    config_load vpn
    config_get enabled settings enabled 0
    [ "$enabled" = "1" ] || { logger -t "VPN" "Disabled"; return 0; }

    local sub_url
    config_get sub_url settings subscription_url ""
    [ -n "$sub_url" ] && { vpn-subscription.sh & sleep 2; }

    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn 60 5 3
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall sing-box 2>/dev/null
    ip link delete tun0 2>/dev/null
    rm -f /tmp/sing-box.json /tmp/geo/geoip-ru.srs /tmp/geo/geosite-ru.srs
}

reload_service() {
    stop_service
    sleep 1
    start_service
}
